In [1]:
import pandas as pd

meeting_note_csv_path = "./guitar_final.csv"
df_rttm = pd.read_csv(meeting_note_csv_path, sep='|')

display(df_rttm)

,start,end,speaker_id,duration,text
0,0.824094,30.169719,SPEAKER_01,29.345625,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...
1,32.414094,42.707844,SPEAKER_00,10.293750,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...
2,41.695344,44.007219,SPEAKER_01,2.311875,"네, 됐어요. 시작하시죠.\n"
3,45.812844,67.058469,SPEAKER_00,21.245625,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...
4,67.227219,82.752219,SPEAKER_01,15.525000,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\..."
5,84.659094,102.529719,SPEAKER_00,17.870625,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...
6,103.474719,117.497844,SPEAKER_01,14.023125,그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 ...
7,119.742219,138.659094,SPEAKER_00,18.916875,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루..."
8,139.334094,168.915969,SPEAKER_01,29.581875,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...
9,170.890344,192.237219,SPEAKER_00,21.346875,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...
10,192.321594,193.587219,SPEAKER_01,1.265625,NaN
11,192.794094,193.452219,SPEAKER_00,0.658125,NaN
12,193.958469,216.554094,SPEAKER_01,22.595625,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...
13,218.562219,238.137219,SPEAKER_00,19.575000,비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문...
14,238.137219,238.626594,SPEAKER_01,0.489375,NaN
15,238.154094,239.335344,SPEAKER_00,1.181250,결국은 본인이 선택한...\n
16,239.875344,240.567219,SPEAKER_01,0.691875,NaN
17,240.567219,240.786594,SPEAKER_00,0.219375,NaN
18,241.090344,251.282844,SPEAKER_01,10.192500,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...
19,253.679094,271.532844,SPEAKER_00,17.853750,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...
20,272.140344,304.506594,SPEAKER_01,32.366250,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...
21,306.970344,325.988469,SPEAKER_00,19.018125,"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타..."
22,326.342844,335.438469,SPEAKER_01,9.095625,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...
23,337.564719,355.874094,SPEAKER_00,18.309375,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...
24,356.262219,363.957219,SPEAKER_01,7.695000,"아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"
25,365.965344,381.422844,SPEAKER_00,15.457500,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 ..."
26,382.182219,383.700969,SPEAKER_01,1.518750,어? 지금 도망가시는 건가요?\n
27,385.709094,397.150344,SPEAKER_00,11.441250,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...
28,397.639719,399.074094,SPEAKER_01,1.434375,NaN
29,401.436594,406.566594,SPEAKER_00,5.130000,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n
30,407.477844,408.304719,SPEAKER_01,0.826875,화난 것 같은데?\n
31,410.093469,417.417219,SPEAKER_00,7.323750,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으..."
32,417.754719,421.197219,SPEAKER_01,3.442500,아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n
33,423.644094,429.314094,SPEAKER_00,5.670000,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n

In [2]:
# 이름 넣기
name_dict = {
    "SPEAKER_00": "AI",
    "SPEAKER_01": "이성용",
}

df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict[x])

display(df_rttm)

,start,end,speaker_id,duration,text,name
0,0.824094,30.169719,SPEAKER_01,29.345625,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,이성용
1,32.414094,42.707844,SPEAKER_00,10.293750,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.695344,44.007219,SPEAKER_01,2.311875,"네, 됐어요. 시작하시죠.\n",이성용
3,45.812844,67.058469,SPEAKER_00,21.245625,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...,AI
4,67.227219,82.752219,SPEAKER_01,15.525000,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",이성용
5,84.659094,102.529719,SPEAKER_00,17.870625,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,AI
6,103.474719,117.497844,SPEAKER_01,14.023125,그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 ...,이성용
7,119.742219,138.659094,SPEAKER_00,18.916875,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루...",AI
8,139.334094,168.915969,SPEAKER_01,29.581875,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,이성용
9,170.890344,192.237219,SPEAKER_00,21.346875,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...,AI
10,192.321594,193.587219,SPEAKER_01,1.265625,NaN,이성용
11,192.794094,193.452219,SPEAKER_00,0.658125,NaN,AI
12,193.958469,216.554094,SPEAKER_01,22.595625,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...,이성용
13,218.562219,238.137219,SPEAKER_00,19.575000,비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문...,AI
14,238.137219,238.626594,SPEAKER_01,0.489375,NaN,이성용
15,238.154094,239.335344,SPEAKER_00,1.181250,결국은 본인이 선택한...\n,AI
16,239.875344,240.567219,SPEAKER_01,0.691875,NaN,이성용
17,240.567219,240.786594,SPEAKER_00,0.219375,NaN,AI
18,241.090344,251.282844,SPEAKER_01,10.192500,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,이성용
19,253.679094,271.532844,SPEAKER_00,17.853750,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,AI
20,272.140344,304.506594,SPEAKER_01,32.366250,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...,이성용
21,306.970344,325.988469,SPEAKER_00,19.018125,"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...",AI
22,326.342844,335.438469,SPEAKER_01,9.095625,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,이성용
23,337.564719,355.874094,SPEAKER_00,18.309375,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,AI
24,356.262219,363.957219,SPEAKER_01,7.695000,"아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n",이성용
25,365.965344,381.422844,SPEAKER_00,15.457500,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 ...",AI
26,382.182219,383.700969,SPEAKER_01,1.518750,어? 지금 도망가시는 건가요?\n,이성용
27,385.709094,397.150344,SPEAKER_00,11.441250,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,AI
28,397.639719,399.074094,SPEAKER_01,1.434375,NaN,이성용
29,401.436594,406.566594,SPEAKER_00,5.130000,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n,AI
30,407.477844,408.304719,SPEAKER_01,0.826875,화난 것 같은데?\n,이성용
31,410.093469,417.417219,SPEAKER_00,7.323750,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으...",AI
32,417.754719,421.197219,SPEAKER_01,3.442500,아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n,이성용
33,423.644094,429.314094,SPEAKER_00,5.670000,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,AI

In [3]:
meeting_note_txt = df_rttm[['start', 'end', 'name', 'text']].to_json(orient='records', force_ascii=False)
print(meeting_note_txt)

[{"start":0.82409375,"end":30.16971875,"name":"이성용","text":"지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 되요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n"},{"start":32.41409375,"end":42.70784375,"name":"AI","text":"좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n네 맞아요. 준비 되셨나요?\n"},{"start":41.69534375,"end":44.00721875,"name":"이성용","text":"네, 됐어요. 시작하시죠.\n"},{"start":45.81284375,"end":67.05846875,"name":"AI","text":"좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n"},{"start":67.22721875,"end":82.75221875,"name":"이성용","text":"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 싼 기타 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n"},{"start":84.65909375,"end":102.52971875,"name":"AI","text":"그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면\n"},{"start":103.47471875,"end":117.49784375,"name":"이성용","text":"그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n"},{"start":119.74221875,"end":138.65909375,"name":"AI","text":"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n"},{"start":139.33409375,"end":168.91596875,"name":"이성용","text":"충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때 안될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n"},{"start":170.89034375,"end":192.23721875,"name":"AI","text":"하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n"},{"start":192.32159375,"end":193.58721875,"name":"이성용","text":null},{"start":192.79409375,"end":193.45221875,"name":"AI","text":null},{"start":193.95846875,"end":216.55409375,"name":"이성용","text":"아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n"},{"start":218.56221875,"end":238.13721875,"name":"AI","text":"비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n"},{"start":238.13721875,"end":238.62659375,"name":"이성용","text":null},{"start":238.15409375,"end":239.33534375,"name":"AI","text":"결국은 본인이 선택한...\n"},{"start":239.87534375,"end":240.56721875,"name":"이성용","text":null},{"start":240.56721875,"end":240.78659375,"name":"AI","text":null},{"start":241.09034375,"end":251.28284375,"name":"이성용","text":"근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n"},{"start":253.67909375,"end":271.53284375,"name":"AI","text":"맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n"},{"start":272.14034375,"end":304.50659375,"name":"이성용","text":"아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n"},{"start":306.97034375,"end":325.98846875,"name":"AI","text":"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠.\n"},{"start":326.34284375,"end":335.43846875,"name":"이성용","text":"맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n"},{"start":337.56471875,"end":355.87409375,"name":"AI","text":"그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n"},{"start":356.26221875,"end":363.95721875,"name":"이성용","text":"아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"},{"start":365.96534375,"end":381.42284375,"name":"AI","text":"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n"},{"start":382.18221875,"end":383.70096875,"name":"이성용","text":"어? 지금 도망가시는 건가요?\n"},{"start":385.70909375,"end":397.15034375,"name":"AI","text":"아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n"},{"start":397.63971875,"end":399.07409375,"name":"이성용","text":null},{"start":401.43659375,"end":406.56659375,"name":"AI","text":"아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"},{"start":407.47784375,"end":408.30471875,"name":"이성용","text":"화난 것 같은데?\n"},{"start":410.09346875,"end":417.41721875,"name":"AI","text":"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요.\n"},{"start":417.75471875,"end":421.19721875,"name":"이성용","text":"아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n"},{"start":423.64409375,"end":429.31409375,"name":"AI","text":"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]

In [4]:
system_prompt = f'''
너는 회의 내용을 요약하는 봇이다. 아래 회의록을 읽고 회의록 양식에 맞게 정리하라.
반드시 아래 키를 가진 JSON 객체로만 답하라. 회의록에서 알 수 없는 항목은 빈 문자열("")로 둔다.

- date: 날짜
- time: 시간
- place: 장소
- writer: 작성자
- attendees: 참석자 (문자열)
- purpose: 목적(목표) (문자열)
- topic: 주제 (문자열)
- content: 회의 내용 (문자열 리스트, 핵심 내용을 항목별로)
- conclusion: 결론 및 합의 (문자열 리스트)
- todo: 할 일 (문자열 리스트)
- notes: 참고 사항 (문자열)

=============== 이하 회의록 ===============

{ meeting_note_txt }
'''

In [6]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv('OPEN_API_KEY')
client = OpenAI(api_key=api_key)

In [7]:
import json

response = client.chat.completions.create(
    model='gpt-4o',
    temperature=0.1,
    response_format={"type": "json_object"},
    messages=[{"role": "system", "content": system_prompt}]
)

summary = response.choices[0].message.content.strip()
summary_json = json.loads(summary)
print(summary_json)

{'date': '', 'time': '', 'place': '', 'writer': '', 'attendees': '이성용, AI', 'purpose': '기타 구매 시 싼 기타와 비싼 기타 중 어떤 것이 더 나은 선택인지 토론', 'topic': '기타 구매 시 싼 기타와 비싼 기타 중 선택', 'content': ['싼 기타로 시작하는 것이 초보자에게 부담이 적고 실수에 대한 걱정이 덜하다.', '비싼 기타로 시작하면 이중 지출을 막을 수 있고, 책임감이 생겨 연습에 더 열중할 수 있다.', '싼 기타도 요즘 품질이 좋아 연습용으로 충분하다.', '비싼 기타는 연주하기 편하고 소리가 좋지만, 초보자는 그 차이를 느끼기 어려울 수 있다.', '비싼 기타는 동기부여가 될 수 있지만, 부담이 커질 수도 있다.', '결국 각자의 스타일과 상황에 맞게 선택하는 것이 중요하다.'], 'conclusion': ['어떤 기타를 선택하든 꾸준히 연습하는 것이 가장 중요하다.', '기타를 사랑하는 마음이 중요하다.'], 'todo': [], 'notes': '토론은 즐겁게 진행되었으며, 기타에 대한 열정을 느낄 수 있었다.'}

In [8]:
with open('./guitar_summary.md', 'w', encoding='utf-8') as f:
    f.write(summary)

In [9]:
df_meeting_note = df_rttm[['start', 'end', 'name', 'text']].copy()
df_meeting_note.dropna(inplace=True)

meeting_note_dict = df_meeting_note.to_dict(orient='records')  # 딕셔너리 형태로 변환
meeting_note_dict

[{'start': 0.8240937500000001,
  'end': 30.16971875,
  'name': '이성용',
  'text': '지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 되요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n'},
 {'start': 32.41409375,
  'end': 42.70784375,
  'name': 'AI',
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n네 맞아요. 준비 되셨나요?\n'},
 {'start': 41.69534375,
  'end': 44.00721875,
  'name': '이성용',
  'text': '네, 됐어요. 시작하시죠.\n'},
 {'start': 45.812843750000006,
  'end': 67.05846875,
  'name': 'AI',
  'text': '좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n'},
 {'start': 67.22721875,
  'end': 82.75221875000001,
  'name': '이성용',
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 싼 기타 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n'},
 {'start': 84.65909375000001,
  'end': 102.52971875,
  'name': 'AI',
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면\n'},
 {'start': 103.47471875,
  'end': 117.49784375,
  'name': '이성용',
  'text': '그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n'},
 {'start': 119.74221875,
  'end': 138.65909375,
  'name': 'AI',
  'text': '하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n'},
 {'start': 139.33409375000002,
  'end': 168.91596875000002,
  'name': '이성용',
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때 안될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n'},
 {'start': 170.89034375,
  'end': 192.23721875,
  'name': 'AI',
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n'},
 {'start': 193.95846875,
  'end': 216.55409375,
  'name': '이성용',
  'text': '아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n'},
 {'start': 218.56221875000003,
  'end': 238.13721875,
  'name': 'AI',
  'text': '비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n'},
 {'start': 238.15409375,
  'end': 239.33534375,
  'name': 'AI',
  'text': '결국은 본인이 선택한...\n'},
 {'start': 241.09034375,
  'end': 251.28284375,
  'name': '이성용',
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n'},
 {'start': 253.67909375,
  'end': 271.53284375000004,
  'name': 'AI',
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n'},
 {'start': 272.14034375,
  'end': 304.50659375000004,
  'name': '이성용',
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n'},
 {'start': 306.97034375000004,
  'end': 325.98846875000004,
  'name': 'AI',
  'text': '하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠.\n'},
 {'start': 326.34284375000004,
  'end': 335.43846875,
  'name': '이성용',
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n'},
 {'start': 337.56471875,
  'end': 355.87409375000004,
  'name': 'AI',
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n'},
 {'start': 356.26221875000005,
  'end': 363.95721875,
  'name': '이성용',
  'text': '아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n'},
 {'start': 365.9653437500001,
  'end': 381.42284375,
  'name': 'AI',
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n'},
 {'start': 382.18221875,
  'end': 383.70096875,
  'name': '이성용',
  'text': '어? 지금 도망가시는 건가요?\n'},
 {'start': 385.70909375,
  'end': 397.1503437500001,
  'name': 'AI',
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n'},
 {'start': 401.43659375,
  'end': 406.56659375,
  'name': 'AI',
  'text': '아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n'},
 {'start': 407.47784375,
  'end': 408.30471875,
  'name': '이성용',
  'text': '화난 것 같은데?\n'},
 {'start': 410.09346875,
  'end': 417.41721875,
  'name': 'AI',
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요.\n'},
 {'start': 417.75471875000005,
  'end': 421.1972187500001,
  'name': '이성용',
  'text': '아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n'},
 {'start': 423.64409375,
  'end': 429.31409375,
  'name': 'AI',
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n'}]

In [10]:
for row in meeting_note_dict:    
    if not isinstance(row['text'], str): # 텍스트가 아닌 다른 형식인 경우 통과
        continue

    correction_system_prompt = f'''
        너는 주어진 회의 녹취록을 수정 및 보완하는 봇이다.
        주어진 회의 녹취록은 STT로 작성된 결과이므로, 이 중에 오류가 있는 부분을 찾아내고 수정하라.

        표현, 말투는 최대한 원본과 일치하도록 유지하되, 잘못 받아적은 내용을 수정하라.
        원본의 내용을 최대한 살리되, 잘못된 내용만 수정하라. 
        어떤 경우에는 A라는 사람이 말한 내용을 B가 말한 것으로 잘못 기록된 경우도 있을 수 있다. 이런 경우에는 문맥을 고려하여 수정하라.

        원본 내용 중 빠지거나, 추가되거나, 잘못 기록된 부분을 찾아내어 수정하라. 수정된 메시지 이외에는 아무것도 작성하지 말라.
        --------------------------------
        회의 요약문 : {summary}
        --------------------------------
        회의 녹취록 전문: {df_meeting_note.to_json(orient='records', force_ascii=False)}
        --------------------------------
        확인할 메시지 원본: {row['text']}
    '''

    # limit token 을 초과했을 때 발생하는 에러는 무시하고 다음 Cell 진행
    response = client.chat.completions.create(
        model='gpt-4o',
        temperature=0.1,
        messages=[
            {"role": "system", "content": correction_system_prompt},
        ]
    )

    correction = response.choices[0].message.content
    if ':' in correction:  # “수정: “ 과 같은 형식으로 반환되는 경우 해결 
        correction = correction.split(':')[-1]
        
    correction = correction.strip() # 좌우 공백 제거

    print(row['name'])
    print(row['text'])
    print(correction)
    print('-----------------')

    row['corrected_text'] = correction

이성용
지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 되요 자연스럽게
그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
두 중에 어떤 역할 맡으실래요?

지금부터 저랑 그 역할극을 합시다. 역할극을 스탠딩 코미디 스타일로 할 건데, 토론을 하면서 자연스럽게 대화하는 형식으로 코미디를 진행해봅시다. 그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요. 그리고 주제는 싼 기타로 시작하는 게 좋으냐, 아니면 비싼 기타로 시작하는 게 좋으냐입니다. 이거를 입장을 나눠가지고 저랑 토론해보면 좋을 것 같아요. 두 중에 어떤 역할 맡으실래요?
-----------------
AI
좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?
네 맞아요. 준비 되셨나요?

좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성용님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?
네 맞아요. 준비 되셨나요?
-----------------
이성용
네, 됐어요. 시작하시죠.

네, 준비됐어요. 시작하시죠.
-----------------
AI
좋아요.
먼저 3기타로 시작하는게
좋은 이유를 말씀드리겠습니다.
초보자일때는
실수도 많고 기타에 익숙해지는
과정이 필요하니까 비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?

좋아요.
먼저 싼 기타로 시작하는 게
좋은 이유를 말씀드리겠습니다.
초보자일 때는
실수도 많고 기타에 익숙해지는
과정이 필요하니까 비싼 기타보다는 부담 없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드하는 것도 나쁘지 않죠?
성용님은 어떻게 생각하세요?
-----------------
이성용
아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타 사고 싼 기타 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.

아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타 사고 싼 기타 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.
-----------------
AI
그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실습을 많이 하니까 더 크지 않을까요?
초보 때는 실습을 많이 하니까
쌍기타로 마음 편히 연습할 수 있는게
더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면

그런데 비싼 기타로 시작하면 혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요? 초보 때는 실수가 많으니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요. 그리고 기타 연주에 익숙해지면
-----------------
이성용
그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데
기타를 싼 거 산다고 달라지나요?

그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데,
기타를 싼 거 산다고 달라지나요?
-----------------
AI
하하, 기타를 망치로 치진 않지만
그래도 초보자들은 실수도 많고
조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에
부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요
그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.
그리고 쌍기타도 요즘은
통질이 꽤 좋아서 연습용으로

하하, 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요. 비싼 기타를 사기 전에 부담없이 연습하면서 자신감을 키우는 것도 중요하다고 생각해요. 그리고 싼 기타도 요즘은 품질이 꽤 좋아서 연습용으로 충분하다고 생각해요.
-----------------
이성용
충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이
많이 좋아서
연습하는데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?
그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때 안될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요

충분하죠. 아 맞아요. 그것도 맞는 말이에요. 싼 기타도 요새 품질이 많이 좋아서 연습하는데 충분한 거는 맞는데, 근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요? 그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때, 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠. 근데 기타가 좋은 기타다. 그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.
-----------------
AI
하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.
쌍기타로 시작해서
부담없이 연습하고
정말 기타에 흥미가 생기면 그때 비슷하게 부담없이 연습하고
정말 기타에 흥미가 생기면
그때 비싼 기타로 넘어가는 것도 좋은 방법이죠

하하, 역시 좋은 기타를 사면 책임감도 더 커진다는 말씀이시군요. 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요. 싼 기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비싼 기타로 넘어가는 것도 좋은 방법이죠.
-----------------
이성용
아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는
측면에서도 비싼 기타가 훨씬 도움이 된다고
생각을 합니다.

아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 좋잖아요. 그러니까 흥미를 더 쉽게 유지할 수 있어요. 그리고 비싼 기타를 사면 흥미를 잃게 되더라도 "어, 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?"라는 생각이 들면서 계속 연습을 열심히 할 수가 있어요. 그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각을 합니다.
-----------------
AI
비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.
하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.

비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.
하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드할 때 그 성취감도 크니까요.
-----------------

KeyboardInterrupt:

In [11]:
# meeting_note_dict json 파일로 저장
import json

with open('./guitar_meeting_note_corrected.json', 'w', encoding='utf-8') as f:
    json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [12]:
md_template = ""

for row in meeting_note_dict:
    # corrected_text 키가 있는 경우 (Limit Token 문제로 인해 없는 경우가 있음)
    if 'corrected_text' in row:
        md_template += f"- **{row['name']}** : {row['corrected_text']} \n"
    else:
        md_template += f"- **{row['name']}** : {row['text']} \n"
with open('./guitar_meeting_note_corrected.md', 'w', encoding='utf-8') as f:
    f.write(md_template)

In [13]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting lxml>=3.1.0 (from python-docx)
  Downloading lxml-6.1.3-cp312-cp312-macosx_10_13_universal2.whl.metadata (3.3 kB)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/anaconda3/envs/llm/lib/python3.12/site-packages (from python-docx) (4.16.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Downloading lxml-6.1.3-cp312-cp312-macosx_10_13_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 4.7 MB/s  0:00:01 eta 0:00:01
Installing collected packages: lxml, python-docx
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [python-docx]
Successfully installed lxml-6.1.3 python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [14]:
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

def to_text(v):  # 리스트면 "- 항목" 줄바꿈 형태로
    return "\n".join(f"- {x}" for x in v) if isinstance(v, list) else (v or "")

def shade(cell, color="DDE9D6"):  # 라벨 칸 연두색 배경
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear'); shd.set(qn('w:color'), 'auto'); shd.set(qn('w:fill'), color)
    tcPr.append(shd)

def set_cell(cell, text, bold=False, center=False):
    cell.text = ""
    for i, line in enumerate(text.split("\n") if text else [""]):
        p = cell.paragraphs[0] if i == 0 else cell.add_paragraph()
        run = p.add_run(line); run.bold = bold; run.font.size = Pt(10.5)
        run.font.name = "맑은 고딕"
        run._element.rPr.rFonts.set(qn('w:eastAsia'), "맑은 고딕")
        if center: p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER if center else WD_ALIGN_VERTICAL.TOP

document = Document()
document.add_heading('회의록', level=1).alignment = WD_ALIGN_PARAGRAPH.CENTER

table = document.add_table(rows=0, cols=4)
table.style = 'Table Grid'
table.alignment = WD_TABLE_ALIGNMENT.CENTER
widths = [Cm(2.8), Cm(5.2), Cm(2.8), Cm(5.2)]

def add_row(height):
    row = table.add_row()
    for c, w in zip(row.cells, widths): c.width = w
    row.height = Cm(height)
    return row

# 날짜 | 시간  /  장소 | 작성자
for l1, k1, l2, k2 in [("날짜", "date", "시간", "time"), ("장소", "place", "작성자", "writer")]:
    r = add_row(1.0).cells
    for i, (txt, is_label) in enumerate([(l1, True), (to_text(summary_json[k1]), False),
                                         (l2, True), (to_text(summary_json[k2]), False)]):
        set_cell(r[i], txt, bold=is_label, center=is_label)
        if is_label: shade(r[i])

# 나머지 항목: 라벨 + 오른쪽 칸 병합
rows = [("참석자", "attendees", 1.0), ("목적(목표)", "purpose", 1.0), ("주제", "topic", 1.0),
        ("회의 내용", "content", 8.0), ("결론 및 합의", "conclusion", 2.5),
        ("할 일", "todo", 2.5), ("참고 사항", "notes", 1.5)]
for label, key, h in rows:
    r = add_row(h).cells
    set_cell(r[0], label, bold=True, center=True); shade(r[0])
    set_cell(r[1].merge(r[3]), to_text(summary_json.get(key, "")))

document.save('./guitar_summary.docx')